title: "5th EOU Fledglings Meeting"
description: "European Ornithologists' Union | Gdańsk, 27–29 March 2026"
author: "EOU Fledglings Committee"
email: eoufledglingmeeting@gmail.com

url: "https://eou-fledglings.github.io"
baseurl: "/2026"

include:
  - _pages
  
header_pages:
  - index.md
  - _pages/programme.md
  - _pages/registration.md
  - _pages/travel.md
  - _pages/Interesting_spots.md
  - _pages/committee.md
  
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

collections:
  pages:
    output: true
    permalink: /:path/

social_links:
  email: eoufledglingmeeting@gmail.com
  twitter: https://twitter.com/EOUnion
  website: https://www.eou.eu/

show_excerpts: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

      
